### ISSUE TITLE
PR OPENED trigger does not trigger a scan, Jenkins doesn't create a PR job until the next event triggering a scan

### ISSUE THREAD

**Issue by agarthetiger** [ParameterizedBuilds/parameterized-builds#232]
- _Parameterized Builds for Jenkins_ plugin version 4.0.8
- _Bitbucket_ version BitBucket Server v6.4.1
- _Jenkins_ Version v2.150.1
- _Jenkins_ Plugin Bitbucket Branch Source Plugin v2.5.0

## Expected behaviour

With `PR OPENED` configured as a trigger, opening a PR in Bitbucket triggers a scan so that Jenkins builds the PR as per the Jenkins multi-branch configuration, which is configured to build the result of the merge.

## Actual behaviour

With `PR OPENED` configured as a trigger, opening a PR in Bitbucket triggers a build of the source branch. Subsequent `PUSH EVENTS` trigger a scan in Jenkins and only after the scan is the PR job created and built as per the Jenkins multi-branch job configuration.

## Description

We're using Bitbucket and Jenkins to build Pull Requests. We want to build the result of the merge and only allow the PR to be merged if this build passes, as well as the code receiving the mandatory approvals. Jenkins is configured to build the result of the merge and verify the result of the merge in the PR. The Jenkins job is a "Bitbucket Team/Project" using the [Bitbucket Branch Source Plugin](https://plugins.jenkins.io/cloudbees-bitbucket-branch-source)

Opening a PR, as per [the documentation](https://github.com/KyleLNicholls/parameterized-builds#multibranch-pipeline-setup) is not triggering a scan. It is building the branch and reporting this build in the pull request, but the branch build is not the same as the result of the merge. After additional commits are made, pushing commits fires the `PUSH EVENT` which triggers a rescan, and the PR is found, built and reports the build result to the PR. This is all fine, but what I'd expect is that the PR OPENED event would also trigger a scan so that the newly opened PR gets built as per the Jenkins multi-branch settings, which in my case should build the result of the merge, not just the HEAD of the PR source branch. 

### Parameterized Builds Triggers
![Screenshot 2019-10-30 at 15 07 03](https://user-images.githubusercontent.com/1242023/67872790-63054a00-fb2a-11e9-9d72-a9815dfb63e3.png)

### Jenkins Job
![Screenshot 2019-10-30 at 15 33 16](https://user-images.githubusercontent.com/1242023/67872976-a790e580-fb2a-11e9-9ea0-80a0490ef1ca.png)

**Comment by a-hacker** [comment]
Hi @agarthetiger. Thank you for submitting this very thorough issue. This gives me a lot of good info to consider.

First things first, the current implementation of triggers for multibranch pipelines is not good. I'm totally aware of that and it wasn't meant to be a final solution. Basically, there used to be no way to really trigger multibranch pipelines since the trigger endpoint and general behavior is so different from other job types. The current implementation got something working and I was planning on building from there.

With that being said, different users have different pipeline configurations. For some, the current implementation works well, for others it doesn't. What needs to happen is a way to configure the triggers to work as a user needs them too. I think this will mean having a totally different job form for multibranch pipelines.

Unfortunately, I really don't have the time to work on this anytime soon. I have two other large projects that I'm focused on right now and I only tend to work on new features roughly one day a month. If I had to give a time estimate, I'll probably get to this in a year at my current rate.

If you (or anyone else reading this) happen to be interested in working on this, I'd be happy to help you out in any way. Otherwise, I would not expect this to get done in a reasonable time frame.

**Comment by agarthetiger** [comment]
Hi @a-hacker , thanks for your reply. I really appreciate a) getting a response and b) getting a detailed one, especially with realistic timeframes. I'd much rather have a disapointing but realistic timeframe than an overly optimistic one which gets missed :)  I am really pleased how well this plugin is working overall. For many of our projects which have less concurrent activity, not having the result of the merge built when a PR is opened will probably be acceptable. 

I expect there will be teams here who will be looking for this functionality. As we roll Bitbucket+Jenkins out here I expect if this becomes a priority for us we can see if we can implement and contribute a suitable fix ourselves. After all, it's just a [small matter of programming](https://en.wikipedia.org/wiki/Small_matter_of_programming), right? ;)

**Comment by davemasters1984** [comment]
@agarthetiger just out of interest - if you want it to trigger a scan and use the Bitbucket source plugin to find the pull request branch and do the pre-merging - could you just use the standard Bitbucket webhook to do this? My assumption (and I could be wrong here) is that this particular plugin is really to enable parameters to be sent from Bitbucket which can be picked up in Jenkins jobs; which I don't think you get when triggering a scan?

I'm interested because I _don't_ have the Bitbucket Source plugin in Jenkins, and instead I'm trying to use _this_ plugin to trigger builds passing the source & destination branch names as parameters, which I then use to manually do the pre-merging myself in the pipeline with GIT commands. 

I'm considering whether it would be better to use the Bitbucket source plugin to achieve this instead (like you seem to be doing); but one thing extra this plugin allows me to do is send the PR number and URL, which I can then set as the Jenkins build description and provide a link to the PR;  something I don't think would be possible were I use the Bitbucket source plugin using scans.

**Comment by a-hacker** [comment]
Closing this as enhancements are no longer being worked on.
